/* Lights Out — Board logic

   5x5 grid of lights. Clicking a cell toggles it and its
   4 orthogonal neighbors. Goal: turn all lights off.
   
   Puzzles are generated by starting from all-off and applying
   random toggles, guaranteeing solvability.
*/

var Board = (function () {

  var grid = [];  // 2D array of booleans (true = on)
  var moves = 0;

  function reset() {
    grid = [];
    for (var y = 0; y < Config.rows; y++) {
      grid[y] = [];
      for (var x = 0; x < Config.cols; x++) {
        grid[y][x] = false;
      }
    }
    moves = 0;
  }

  /** Toggle a cell and its neighbors (the core mechanic) */
  function toggle(x, y) {
    if (x < 0 || x >= Config.cols || y < 0 || y >= Config.rows) return;

    // Toggle center
    grid[y][x] = !grid[y][x];
    // Toggle neighbors
    if (x > 0) grid[y][x - 1] = !grid[y][x - 1];
    if (x < Config.cols - 1) grid[y][x + 1] = !grid[y][x + 1];
    if (y > 0) grid[y - 1][x] = !grid[y - 1][x];
    if (y < Config.rows - 1) grid[y + 1][x] = !grid[y + 1][x];

    moves++;
  }

  /**
   * Generate a solvable puzzle by applying N random toggles
   * to an all-off board. This guarantees the puzzle is solvable
   * by reversing those same toggles.
   */
  function generate(numToggles) {
    reset();

    // Apply random toggles (avoid repeating same cell which would cancel out)
    var toggled = {};
    var count = 0;
    var attempts = 0;

    while (count < numToggles && attempts < numToggles * 10) {
      var rx = Math.floor(Math.random() * Config.cols);
      var ry = Math.floor(Math.random() * Config.rows);
      var key = rx + ',' + ry;

      // Allow some repeats for harder puzzles, but try to spread out
      if (!toggled[key] || count > numToggles / 2) {
        toggle(rx, ry);
        toggled[key] = true;
        count++;
      }
      attempts++;
    }

    // Reset move counter (generation moves don't count)
    moves = 0;

    // Make sure at least some lights are on
    if (isSolved()) {
      // Rare edge case — just toggle center
      toggle(2, 2);
      moves = 0;
    }
  }

  /** Check if all lights are off (puzzle solved) */
  function isSolved() {
    for (var y = 0; y < Config.rows; y++) {
      for (var x = 0; x < Config.cols; x++) {
        if (grid[y][x]) return false;
      }
    }
    return true;
  }

  /** Count how many lights are still on */
  function lightsOn() {
    var count = 0;
    for (var y = 0; y < Config.rows; y++) {
      for (var x = 0; x < Config.cols; x++) {
        if (grid[y][x]) count++;
      }
    }
    return count;
  }

  function getGrid() { return grid; }
  function getMoves() { return moves; }

  return {
    reset: reset,
    toggle: toggle,
    generate: generate,
    isSolved: isSolved,
    lightsOn: lightsOn,
    getGrid: getGrid,
    get moves() { return moves; },
  };
})();
