/* Wordle — Word Lists

   TARGET_WORDS: ~300 common 5-letter words used as puzzle answers.
   VALID_GUESSES: ~1200 additional valid 5-letter words accepted as guesses.
   All words are lowercase.

   A guess is valid if it appears in either TARGET_WORDS or VALID_GUESSES.
   The daily target is picked randomly from TARGET_WORDS.
*/

var Words = (function () {

  // --- Target words (~300 common, well-known words) ---
  var TARGET_WORDS = [
    'about','above','abuse','actor','acute','admit','adopt','adult','after','again',
    'agent','agree','ahead','alarm','album','alert','alien','align','alive','alley',
    'allow','alone','along','alter','ample','angel','anger','angle','angry','anime',
    'ankle','annex','apart','apple','apply','arena','argue','arise','armor','array',
    'arrow','aside','asset','atlas','attic','audio','audit','avoid','awake','award',
    'aware','awful','bacon','badge','badly','baker','basic','basin','basis','batch',
    'beach','beard','beast','begin','being','below','bench','berry','birth','black',
    'blade','blame','bland','blank','blast','blaze','bleed','blend','bless','blind',
    'block','blood','bloom','blown','board','boast','bonus','boost','booth','bound',
    'brain','brand','brave','bread','break','breed','brick','bride','brief','bring',
    'broad','broke','brook','brown','brush','buddy','build','bunch','burst','buyer',
    'cabin','cable','camel','candy','cargo','carry','catch','cause','cease','chain',
    'chair','chalk','champ','chaos','charm','chart','chase','cheap','check','cheek',
    'cheer','chess','chest','chief','child','chill','china','choir','chunk','civic',
    'civil','claim','clash','class','clean','clear','clerk','click','cliff','climb',
    'cling','clock','clone','close','cloth','cloud','coach','coast','color','comet',
    'comic','coral','couch','could','count','court','cover','crack','craft','crane',
    'crash','crazy','cream','creek','crime','crisp','cross','crowd','crown','cruel',
    'crush','curve','cycle','daily','dance','death','debug','decay','decor','delay',
    'delta','demon','dense','depot','depth','derby','devil','diary','dirty','disco',
    'ditch','dizzy','dodge','donor','doubt','dough','draft','drain','drake','drama',
    'drank','drape','drawn','dream','dress','dried','drift','drill','drink','drive',
    'drone','drown','drums','drunk','dryer','dusty','dwarf','dying','eager','eagle',
    'early','earth','eight','elder','elect','elite','email','ember','empty','enemy',
    'enjoy','enter','entry','equal','error','essay','event','every','exact','exile',
    'exist','extra','fable','facet','faith','false','fancy','fatal','fault','feast',
    'fence','ferry','fetch','fever','fiber','field','fifth','fifty','fight','final',
    'first','fixed','flame','flash','fleet','flesh','float','flock','flood','floor',
    'flour','fluid','flush','flute','focal','focus','force','forge','forth','forum',
    'found','frame','frank','fraud','fresh','front','frost','froze','fruit','fully',
    'funny','ghost','giant','given','glass','globe','gloom','glory','gloss','glove',
    'going','grace','grade','grain','grand','grant','grape','graph','grasp','grass',
    'grave','great','green','greet','grief','grill','grind','groan','groom','gross',
    'group','grove','grown','guard','guess','guest','guide','guild','guilt','guise',
    'happy','harsh','haste','haven','heart','heavy','hedge','hello','hence','herbs'
  ];

  // --- Additional valid guesses (~1200 words) ---
  var VALID_GUESSES = [
    'aahed','aalii','abaci','aback','abaft','abase','abash','abate','abbey','abbot',
    'abhor','abide','abler','abode','abort','abound','abuzz','abyss','acorn','acrid',
    'acted','acute','adage','added','adder','addle','adept','adieu','admin','adobe',
    'adore','adorn','aegis','afoot','afoul','agape','agate','agave','agent','aging',
    'aglow','agony','agree','aided','aider','aimed','aimer','aired','aisle','alarm',
    'algae','alibi','align','allay','allot','alloy','aloft','alpha','altar','amaze',
    'amber','amble','amend','amino','amiss','amity','among','ample','amuse','angel',
    'angle','angst','anime','annex','annoy','antic','anvil','aorta','aphid','apple',
    'aptly','arbor','ardor','arena','argon','arise','armor','aroma','arose','array',
    'arson','ashen','ashes','aside','asked','asset','atoll','atone','attic','audio',
    'augur','aunty','avail','avert','avian','avoid','await','awash','awful','awoke',
    'axial','axiom','azure','badge','badly','bagel','baggy','baker','balmy','banal',
    'banjo','barge','baron','basal','basic','basil','basin','basis','batch','bathe',
    'baton','bayou','beach','beady','beard','beast','beech','beefy','begin','being',
    'belch','belle','belly','below','bench','berry','berth','beset','bible','bicep',
    'biddy','biker','bilge','billy','binge','biome','birch','birth','bison','bitty',
    'black','blade','blame','bland','blank','blare','blast','blaze','bleak','bleat',
    'bleed','blend','bless','blimp','blind','bliss','blitz','bloat','block','bloke',
    'blond','blood','bloom','blown','blues','bluff','blunt','blurb','blurt','blush',
    'board','boast','bobby','bogey','boggy','bonus','booby','boost','booth','booty',
    'booze','borax','bored','borne','bosom','bossy','botch','bound','bowed','bowel',
    'boxer','brace','braid','brain','brake','brand','brash','brass','brave','brawn',
    'bread','break','breed','briar','bribe','brick','bride','brief','brine','bring',
    'brink','briny','brisk','broad','broil','broke','brood','brook','broth','brown',
    'brush','brute','buddy','budge','buggy','build','built','bulge','bulky','bully',
    'bunch','bunny','burst','bushy','buyer','bylaw','cabal','cabin','cable','cadet',
    'camel','cameo','candy','canny','canoe','caper','cargo','carol','carry','carve',
    'catch','cater','cause','cavil','cedar','chain','chair','chalk','champ','chant',
    'chaos','charm','chart','chase','cheap','cheat','check','cheek','cheer','chess',
    'chest','chick','chief','child','chili','chill','chime','china','chirp','choir',
    'chord','chore','chose','chunk','churn','cider','cigar','cinch','circa','civic',
    'civil','claim','clamp','clang','clank','clash','clasp','class','clean','clear',
    'clerk','click','cliff','climb','cling','cloak','clock','clone','close','cloth',
    'cloud','clout','clown','clubs','cluck','clued','clump','clung','coach','coast',
    'cobra','cocoa','colon','color','comet','comic','comma','conch','coral','corgi',
    'couch','could','count','coupe','court','cover','covet','crack','craft','cramp',
    'crane','crank','crash','crass','crate','crave','crawl','craze','crazy','creak',
    'cream','creek','creep','crest','crime','crimp','crisp','croak','crock','crook',
    'cross','crowd','crown','crude','cruel','crush','crust','cubic','curry','curse',
    'curve','cycle','cynic','daddy','daily','dairy','daisy','dance','dandy','datum',
    'dealt','death','debit','debug','debut','decal','decay','decor','decoy','decry',
    'defer','deity','delay','delta','delve','demon','demur','denim','dense','depot',
    'depth','derby','detox','deuce','devil','diary','dicey','digit','diner','dingy',
    'dirty','disco','ditch','ditto','ditty','diver','dizzy','dodge','dodgy','dogma',
    'doing','dolly','donor','donut','doubt','dough','dowdy','dowel','draft','drain',
    'drake','drama','drank','drape','drawn','dread','dream','dress','dried','drift',
    'drill','drink','drive','droit','droll','drone','drool','droop','dross','drove',
    'drown','drums','drunk','dryer','dryly','ducal','dummy','dunce','dusty','dutch',
    'duvet','dwarf','dwell','dying','eager','eagle','early','earth','easel','eaten',
    'eater','ebony','edged','edict','eight','eject','elbow','elder','elect','elfin',
    'elite','elope','elude','email','ember','emcee','empty','enact','ended','endow',
    'enemy','enjoy','ennui','ensue','enter','entry','envoy','epoch','equal','equip',
    'erase','erode','error','erupt','essay','ether','ethic','evade','event','every',
    'evict','evoke','exact','exalt','excel','exert','exile','exist','expat','expel',
    'extra','exude','exult','fable','facet','fagot','faint','fairy','faith','false',
    'fancy','fatal','fatty','fault','fauna','feast','feign','feint','fella','felon',
    'femur','fence','feral','ferry','fetal','fetch','fetid','fetus','fever','fewer',
    'fiber','fibre','field','fiend','fifth','fifty','fight','filth','final','finch',
    'first','fishy','fixed','fixer','fizzy','fjord','flack','flail','flair','flake',
    'flame','flank','flare','flash','flask','fleet','flesh','flick','flier','fling',
    'flint','float','flock','flood','floor','flora','floss','flour','flout','fluid',
    'fluke','flung','flunk','flush','flute','focal','focus','foggy','folly','foray',
    'force','forge','forgo','forte','forth','forty','forum','fossil','found','foxes',
    'foyer','frail','frame','frank','fraud','freak','freed','fresh','friar','fried',
    'frill','frisk','front','frost','froze','frugal','fruit','fully','fungi','funky',
    'funny','furry','fussy','fuzzy','gaffe','gaily','gamer','gamma','gauge','gaunt',
    'gauze','gavel','gawky','geeky','genie','genre','ghost','giant','giddy','given',
    'giver','gland','glare','glass','glaze','gleam','glean','glide','glint','globe',
    'gloom','glory','gloss','glove','glyph','gnash','gnome','godly','going','golem',
    'golly','goose','gorge','gotta','gouge','gourd','grace','grade','graft','grail',
    'grain','grand','grant','grape','graph','grasp','grass','grate','grave','gravy',
    'graze','great','greed','green','greet','grief','grill','grime','grimy','grind',
    'gripe','groan','groin','groom','grope','gross','group','grout','grove','growl',
    'grown','gruel','gruff','grunt','guard','guava','guess','guest','guide','guild',
    'guilt','guise','gulch','gully','gummy','guppy','gusto','gusty','gutter','habit',
    'hairy','halve','handy','happy','hardy','haste','hasty','hatch','haunt','haven',
    'hazel','heady','heart','heavy','hedge','heist','hello','hence','herbs','heron',
    'hilly','hinge','hippo','hitch','hoard','hobby','homer','honey','honor','hoped',
    'horde','horny','horse','hotel','hotly','hound','house','hover','howdy','human',
    'humid','humor','humps','humus','hurry','hyena','hyper','icily','icing','ideal',
    'idiom','idiot','image','imbue','imply','inane','incur','index','indie','inept',
    'inert','infer','ingot','inner','input','inter','intro','ionic','irate','ivory',
    'jaunt','jazzy','jelly','jewel','jiffy','joint','joker','jolly','joust','judge',
    'juice','juicy','jumbo','jumpy','juror','karma','kayak','kebab','khaki','kinky',
    'knack','knead','kneel','knelt','knife','knock','knoll','known','koala','kudos',
    'label','labor','laden','ladle','lager','lance','lanky','lapel','lapse','large',
    'larva','laser','latch','later','lathe','latte','laugh','layer','leach','leafy',
    'leaky','leapt','learn','lease','leash','least','leave','ledge','legal','lemon',
    'level','lever','light','lilac','limbo','limit','linen','liner','lingo','lipid',
    'liver','llama','lobby','local','locus','lodge','lofty','logic','login','loopy',
    'loose','lorry','loser','lousy','lover','lower','lowly','loyal','lucid','lucky',
    'lumen','lumpy','lunar','lunch','lunge','lusty','lying','lynch','lyric','macro',
    'mafia','magic','major','maker','mamma','mango','manor','maple','march','marry',
    'marsh','mason','match','maxim','maybe','mayor','mealy','media','medic','melee',
    'melon','mercy','merge','merit','merry','metal','meter','midst','might','mimic',
    'mince','minor','minus','mirth','miser','misty','mitre','model','modem','mogul',
    'moist','molar','money','month','moose','moral','morph','mossy','motel','motif',
    'motor','motto','mound','mount','mourn','mouse','mouth','mover','movie','mucus',
    'muddy','mulch','mummy','mural','murky','mushy','music','musty','muted','myrrh',
    'nadir','naive','nanny','nasal','nasty','naval','nerve','never','newly','nexus',
    'niche','night','ninja','noble','nobly','noise','noisy','nomad','north','notch',
    'noted','novel','nudge','nurse','nylon','oasis','occur','ocean','oddly','offal',
    'offer','often','olive','omega','onset','opera','optic','orbit','order','organ',
    'other','otter','ought','ounce','outer','outdo','overt','owner','oxide','ozone',
    'paddy','pagan','paint','panda','panel','panic','papal','paper','party','pasta',
    'paste','patch','patio','pause','peace','peach','pearl','pecan','pedal','penny',
    'perch','peril','perky','petal','petty','phase','phone','photo','piano','piece',
    'pilot','pinch','pixel','pizza','place','plaid','plain','plane','plank','plant',
    'plate','plaza','plead','pleat','plied','pluck','plumb','plume','plump','plunge',
    'plunk','plush','poach','point','poise','poker','polar','polka','polyp','pooch',
    'poppy','porch','poser','posit','posse','pouch','pound','power','prank','prawn',
    'press','price','pride','prime','print','prior','prism','privy','prize','probe',
    'prone','proof','prose','proud','prove','prowl','prude','prune','psalm','pubic',
    'pudgy','pulse','punch','pupil','puppy','purge','purse','pushy','putty','pygmy',
    'quack','quail','qualm','quart','quasi','queen','query','quest','queue','quick',
    'quiet','quill','quirk','quota','quote','rabbi','rabid','radar','radii','radio',
    'rainy','raise','rally','ranch','range','rapid','raven','rayon','reach','react',
    'ready','realm','rebel','rebus','recap','refer','reign','relax','relay','relic',
    'remit','renal','renew','repay','repel','reply','resin','retro','retry','reuse',
    'revel','rider','ridge','rifle','right','rigid','rigor','rinse','risky','rival',
    'river','rivet','roast','robin','robot','rocky','rogue','roman','roost','rouge',
    'rough','round','route','rover','rowdy','royal','rugby','ruler','rumba','rumor',
    'rupee','rural','rusty','sadly','saint','salad','salon','salsa','salty','salve',
    'sandy','saner','satin','sauce','saucy','sauna','savor','savvy','scald','scale',
    'scalp','scant','scare','scarf','scary','scene','scent','scone','scope','score',
    'scout','scowl','scram','scrap','screw','scrub','sedan','seize','sense','serum',
    'serve','setup','seven','sever','shade','shady','shaft','shake','shaky','shall',
    'shame','shape','shard','share','shark','sharp','shawl','shear','sheen','sheep',
    'sheer','sheet','shelf','shell','shift','shine','shiny','shire','shirt','shock',
    'shore','short','shout','shove','shown','showy','shrub','shrug','shunt','siege',
    'sight','sigma','silly','since','siren','sixth','sixty','sized','skate','sketchy',
    'skill','skimp','skull','skunk','slack','slain','slang','slant','slash','slate',
    'sleek','sleep','sleet','slice','slide','slime','slimy','sling','slink','slope',
    'sloth','slump','slung','slunk','small','smart','smash','smell','smelt','smile',
    'smirk','smite','smith','smoke','smoky','snack','snail','snake','snare','snarl',
    'sneak','sneer','snide','sniff','snore','snort','snout','snowy','soapy','sober',
    'solar','solid','solve','sonic','sorry','sound','south','space','spade','spare',
    'spark','spawn','speak','spear','speck','speed','spell','spend','spent','spice',
    'spicy','spied','spike','spill','spine','spoke','spoof','spook','spoon','sport',
    'spout','spray','spree','sprig','spunk','squad','squat','squid','stack','staff',
    'stage','stain','stair','stake','stale','stalk','stall','stamp','stand','stank',
    'stare','stark','start','stash','state','stave','stays','steak','steal','steam',
    'steel','steep','steer','stern','stick','stiff','still','sting','stink','stint',
    'stock','stoic','stoke','stole','stomp','stone','stony','stood','stool','stoop',
    'store','stork','storm','story','stout','stove','strap','straw','stray','strip',
    'strum','strut','stuck','study','stuff','stump','stung','stunk','stunt','style',
    'sugar','suite','sulky','sunny','super','surge','sushi','swamp','swarm','swear',
    'sweat','sweep','sweet','swept','swift','swill','swine','swing','swipe','swirl',
    'swoon','sword','swore','sworn','swung','syrup','tabby','table','tacit','taffy',
    'taint','taken','tally','talon','tango','tapir','tardy','taste','tasty','taunt',
    'tease','teeth','tempo','tense','tenth','tepid','terra','theft','their','theme',
    'there','thick','thief','thigh','thing','think','third','thorn','those','three',
    'threw','throw','thrum','thumb','thump','tiara','tidal','tiger','tight','timer',
    'timid','tipsy','titan','title','toast','today','token','tonic','tooth','topaz',
    'torch','total','touch','tough','towel','tower','toxic','trace','track','trade',
    'trail','train','trait','tramp','trash','trawl','treat','trend','triad','trial',
    'tribe','trick','tried','trite','troll','troop','trout','truce','truck','truly',
    'trump','trunk','trust','truth','tulip','tumor','tuner','tunic','turbo','tutor',
    'twang','tweak','tweed','twice','twine','twist','tying','udder','ulcer','ultra',
    'umbra','uncle','under','undue','unfit','union','unite','unity','unlit','until',
    'upper','upset','urban','usage','usher','usual','utter','vague','valid','valor',
    'value','valve','vapor','vault','vegan','venue','verge','verse','vigor','villa',
    'vinyl','viola','viper','viral','virus','visit','visor','vista','vital','vivid',
    'vocal','vodka','vogue','voice','voila','voter','vouch','vowel','vulva','wacky',
    'wager','wagon','waist','waste','watch','water','weary','weave','wedge','weedy',
    'weigh','weird','whale','wheat','wheel','where','which','while','whine','whirl',
    'white','whole','whose','widen','wider','widow','width','wield','windy','witch',
    'woman','women','world','worry','worse','worst','worth','would','wound','wrack',
    'wrath','wreak','wreck','wring','wrist','wrote','yacht','yearn','yeast','yield',
    'young','youth','zebra','zesty','zippy','zonal'
  ];

  /** Pick a random target word */
  function pickTarget() {
    return TARGET_WORDS[Math.floor(Math.random() * TARGET_WORDS.length)];
  }

  /** Check if a word is a valid guess */
  function isValid(word) {
    var w = word.toLowerCase();
    return TARGET_WORDS.indexOf(w) !== -1 || VALID_GUESSES.indexOf(w) !== -1;
  }

  return {
    pickTarget: pickTarget,
    isValid: isValid,
    get targetCount() { return TARGET_WORDS.length; },
    get guessCount() { return TARGET_WORDS.length + VALID_GUESSES.length; },
  };
})();
